services:
  gcp-emulators:
    image: google/cloud-sdk:latest
    container_name: gcp-emulators
    ports:
      - "8080:8080" # Firestore
      - "8085:8085" # Pub/Sub
      - "9010:9010" # Spanner
      - "9090:9090" # Bigtable
    command: >
      bash -c "gcloud components install pubsub-emulator cloud-firestore-emulator spanner-emulator bigtable-emulator --quiet &&
               gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 &
               gcloud beta emulators firestore start --host-port=0.0.0.0:8080 &
               gcloud beta emulators spanner start --host-port=0.0.0.0:9010 &
               gcloud beta emulators bigtable start --host-port=0.0.0.0:9090"
